//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfProjektFirmy.Model.Entieties
{
    using System;
    using System.Collections.Generic;
    
    public partial class Egzemplarz
    {
        public int IdEgzemplarza { get; set; }
        public int IdKsiazki { get; set; }
        public int RokWydania { get; set; }
        public Nullable<int> IdCzytelnika { get; set; }
        public Nullable<System.DateTime> DataWypozyczenia { get; set; }
        public Nullable<System.DateTime> DataOddania { get; set; }
        public Nullable<int> IdPracownika { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Czytelnik Czytelnik { get; set; }
        public virtual Ksiazka Ksiazka { get; set; }
        public virtual Pracownicy Pracownicy { get; set; }
    }
}
