//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfProjektFirmy.Model.Entieties
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ksiazka_Autor
    {
        public int IdKsiazki { get; set; }
        public int IdAutora { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Autor Autor { get; set; }
        public virtual Ksiazka Ksiazka { get; set; }
    }
}
