//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfProjektFirmy.Model.Entieties
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BibliotekaPlutaLukaszEntities : DbContext
    {
        public BibliotekaPlutaLukaszEntities()
            : base("name=BibliotekaPlutaLukaszEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Autor> Autor { get; set; }
        public virtual DbSet<Czytelnik> Czytelnik { get; set; }
        public virtual DbSet<Egzemplarz> Egzemplarz { get; set; }
        public virtual DbSet<FilieBiblioteki> FilieBiblioteki { get; set; }
        public virtual DbSet<Gatunek> Gatunek { get; set; }
        public virtual DbSet<Ksiazka> Ksiazka { get; set; }
        public virtual DbSet<Ksiazka_Autor> Ksiazka_Autor { get; set; }
        public virtual DbSet<Ksiegarnia> Ksiegarnia { get; set; }
        public virtual DbSet<Pracownicy> Pracownicy { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Zamowienia> Zamowienia { get; set; }
    }
}
