//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReferenceBiblioteka
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WcfProjektFirmy")]
    public partial class CompositeType : object
    {
        
        private bool BoolValueField;
        
        private string StringValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue
        {
            get
            {
                return this.BoolValueField;
            }
            set
            {
                this.BoolValueField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue
        {
            get
            {
                return this.StringValueField;
            }
            set
            {
                this.StringValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AutorForView", Namespace="http://schemas.datacontract.org/2004/07/WcfProjektFirmy")]
    public partial class AutorForView : object
    {
        
        private int IdAutoraField;
        
        private string ImieField;
        
        private string NazwiskoField;
        
        private string OpisField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAutora
        {
            get
            {
                return this.IdAutoraField;
            }
            set
            {
                this.IdAutoraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Imie
        {
            get
            {
                return this.ImieField;
            }
            set
            {
                this.ImieField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nazwisko
        {
            get
            {
                return this.NazwiskoField;
            }
            set
            {
                this.NazwiskoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Opis
        {
            get
            {
                return this.OpisField;
            }
            set
            {
                this.OpisField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CzytelnikForView", Namespace="http://schemas.datacontract.org/2004/07/WcfProjektFirmy")]
    public partial class CzytelnikForView : object
    {
        
        private string AdresField;
        
        private int IdCzytelnikaField;
        
        private string ImieField;
        
        private string NazwiskoField;
        
        private int PeselField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adres
        {
            get
            {
                return this.AdresField;
            }
            set
            {
                this.AdresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCzytelnika
        {
            get
            {
                return this.IdCzytelnikaField;
            }
            set
            {
                this.IdCzytelnikaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Imie
        {
            get
            {
                return this.ImieField;
            }
            set
            {
                this.ImieField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nazwisko
        {
            get
            {
                return this.NazwiskoField;
            }
            set
            {
                this.NazwiskoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Pesel
        {
            get
            {
                return this.PeselField;
            }
            set
            {
                this.PeselField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="EgzemplarzForView", Namespace="http://schemas.datacontract.org/2004/07/WcfProjektFirmy")]
    public partial class EgzemplarzForView : object
    {
        
        private string CzytelnikNazwiskoField;
        
        private System.Nullable<System.DateTime> DataOddaniaField;
        
        private System.Nullable<System.DateTime> DataWypozyczeniaField;
        
        private System.Nullable<int> IdCzytelnikaField;
        
        private int IdEgzemplarzaField;
        
        private int IdKsiazkiField;
        
        private System.Nullable<int> IdPracownikaField;
        
        private string KsiazkaTytulField;
        
        private string PracownikNazwiskoField;
        
        private int RokWydaniaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CzytelnikNazwisko
        {
            get
            {
                return this.CzytelnikNazwiskoField;
            }
            set
            {
                this.CzytelnikNazwiskoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataOddania
        {
            get
            {
                return this.DataOddaniaField;
            }
            set
            {
                this.DataOddaniaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataWypozyczenia
        {
            get
            {
                return this.DataWypozyczeniaField;
            }
            set
            {
                this.DataWypozyczeniaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdCzytelnika
        {
            get
            {
                return this.IdCzytelnikaField;
            }
            set
            {
                this.IdCzytelnikaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEgzemplarza
        {
            get
            {
                return this.IdEgzemplarzaField;
            }
            set
            {
                this.IdEgzemplarzaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdKsiazki
        {
            get
            {
                return this.IdKsiazkiField;
            }
            set
            {
                this.IdKsiazkiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdPracownika
        {
            get
            {
                return this.IdPracownikaField;
            }
            set
            {
                this.IdPracownikaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KsiazkaTytul
        {
            get
            {
                return this.KsiazkaTytulField;
            }
            set
            {
                this.KsiazkaTytulField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PracownikNazwisko
        {
            get
            {
                return this.PracownikNazwiskoField;
            }
            set
            {
                this.PracownikNazwiskoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RokWydania
        {
            get
            {
                return this.RokWydaniaField;
            }
            set
            {
                this.RokWydaniaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FilieForView", Namespace="http://schemas.datacontract.org/2004/07/WcfProjektFirmy")]
    public partial class FilieForView : object
    {
        
        private string AdresField;
        
        private int IdFiliField;
        
        private string NazwaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adres
        {
            get
            {
                return this.AdresField;
            }
            set
            {
                this.AdresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFili
        {
            get
            {
                return this.IdFiliField;
            }
            set
            {
                this.IdFiliField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nazwa
        {
            get
            {
                return this.NazwaField;
            }
            set
            {
                this.NazwaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="GatunekForView", Namespace="http://schemas.datacontract.org/2004/07/WcfProjektFirmy")]
    public partial class GatunekForView : object
    {
        
        private int IdGatunkuField;
        
        private string NazwaGatunkuField;
        
        private string OpisField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdGatunku
        {
            get
            {
                return this.IdGatunkuField;
            }
            set
            {
                this.IdGatunkuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NazwaGatunku
        {
            get
            {
                return this.NazwaGatunkuField;
            }
            set
            {
                this.NazwaGatunkuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Opis
        {
            get
            {
                return this.OpisField;
            }
            set
            {
                this.OpisField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KsiazkaForView", Namespace="http://schemas.datacontract.org/2004/07/WcfProjektFirmy")]
    public partial class KsiazkaForView : object
    {
        
        private string GatunekNazwaField;
        
        private int IdGatunkuField;
        
        private int IdKsiazkiField;
        
        private System.Nullable<int> LiczbaEgzDostepnychField;
        
        private string TytulField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GatunekNazwa
        {
            get
            {
                return this.GatunekNazwaField;
            }
            set
            {
                this.GatunekNazwaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdGatunku
        {
            get
            {
                return this.IdGatunkuField;
            }
            set
            {
                this.IdGatunkuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdKsiazki
        {
            get
            {
                return this.IdKsiazkiField;
            }
            set
            {
                this.IdKsiazkiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> LiczbaEgzDostepnych
        {
            get
            {
                return this.LiczbaEgzDostepnychField;
            }
            set
            {
                this.LiczbaEgzDostepnychField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tytul
        {
            get
            {
                return this.TytulField;
            }
            set
            {
                this.TytulField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KsiegarniaForView", Namespace="http://schemas.datacontract.org/2004/07/WcfProjektFirmy")]
    public partial class KsiegarniaForView : object
    {
        
        private string AdresField;
        
        private int IdKsiegarniField;
        
        private string NazwaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adres
        {
            get
            {
                return this.AdresField;
            }
            set
            {
                this.AdresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdKsiegarni
        {
            get
            {
                return this.IdKsiegarniField;
            }
            set
            {
                this.IdKsiegarniField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nazwa
        {
            get
            {
                return this.NazwaField;
            }
            set
            {
                this.NazwaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PracownicyForView", Namespace="http://schemas.datacontract.org/2004/07/WcfProjektFirmy")]
    public partial class PracownicyForView : object
    {
        
        private string FiliaNazwaField;
        
        private System.Nullable<int> IdFiliiField;
        
        private int IdPracownikaField;
        
        private string ImieField;
        
        private string NazwiskoField;
        
        private string PeselField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FiliaNazwa
        {
            get
            {
                return this.FiliaNazwaField;
            }
            set
            {
                this.FiliaNazwaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdFilii
        {
            get
            {
                return this.IdFiliiField;
            }
            set
            {
                this.IdFiliiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPracownika
        {
            get
            {
                return this.IdPracownikaField;
            }
            set
            {
                this.IdPracownikaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Imie
        {
            get
            {
                return this.ImieField;
            }
            set
            {
                this.ImieField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nazwisko
        {
            get
            {
                return this.NazwiskoField;
            }
            set
            {
                this.NazwiskoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pesel
        {
            get
            {
                return this.PeselField;
            }
            set
            {
                this.PeselField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ZamowieniaForView", Namespace="http://schemas.datacontract.org/2004/07/WcfProjektFirmy")]
    public partial class ZamowieniaForView : object
    {
        
        private System.Nullable<int> IdKsiazkiField;
        
        private System.Nullable<int> IdKsiegarniField;
        
        private System.Nullable<int> IdPracownikaField;
        
        private int IdZamowieniaField;
        
        private string KsiazkaTytulField;
        
        private string KsiegarniaNazwaField;
        
        private string PracownikNazwiskoField;
        
        private System.Nullable<int> RokWydaniaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdKsiazki
        {
            get
            {
                return this.IdKsiazkiField;
            }
            set
            {
                this.IdKsiazkiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdKsiegarni
        {
            get
            {
                return this.IdKsiegarniField;
            }
            set
            {
                this.IdKsiegarniField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdPracownika
        {
            get
            {
                return this.IdPracownikaField;
            }
            set
            {
                this.IdPracownikaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdZamowienia
        {
            get
            {
                return this.IdZamowieniaField;
            }
            set
            {
                this.IdZamowieniaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KsiazkaTytul
        {
            get
            {
                return this.KsiazkaTytulField;
            }
            set
            {
                this.KsiazkaTytulField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KsiegarniaNazwa
        {
            get
            {
                return this.KsiegarniaNazwaField;
            }
            set
            {
                this.KsiegarniaNazwaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PracownikNazwisko
        {
            get
            {
                return this.PracownikNazwiskoField;
            }
            set
            {
                this.PracownikNazwiskoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> RokWydania
        {
            get
            {
                return this.RokWydaniaField;
            }
            set
            {
                this.RokWydaniaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Autor", Namespace="http://schemas.datacontract.org/2004/07/WcfProjektFirmy.Model.Entieties")]
    public partial class Autor : object
    {
        
        private int IdAutoraField;
        
        private string ImieField;
        
        private System.Nullable<bool> IsActiveField;
        
        private System.Collections.Generic.List<ServiceReferenceBiblioteka.Ksiazka_Autor> Ksiazka_AutorField;
        
        private string NazwiskoField;
        
        private string OpisField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAutora
        {
            get
            {
                return this.IdAutoraField;
            }
            set
            {
                this.IdAutoraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Imie
        {
            get
            {
                return this.ImieField;
            }
            set
            {
                this.ImieField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsActive
        {
            get
            {
                return this.IsActiveField;
            }
            set
            {
                this.IsActiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceReferenceBiblioteka.Ksiazka_Autor> Ksiazka_Autor
        {
            get
            {
                return this.Ksiazka_AutorField;
            }
            set
            {
                this.Ksiazka_AutorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nazwisko
        {
            get
            {
                return this.NazwiskoField;
            }
            set
            {
                this.NazwiskoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Opis
        {
            get
            {
                return this.OpisField;
            }
            set
            {
                this.OpisField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ksiazka_Autor", Namespace="http://schemas.datacontract.org/2004/07/WcfProjektFirmy.Model.Entieties")]
    public partial class Ksiazka_Autor : object
    {
        
        private ServiceReferenceBiblioteka.Autor AutorField;
        
        private int IdAutoraField;
        
        private int IdKsiazkiField;
        
        private System.Nullable<bool> IsActiveField;
        
        private ServiceReferenceBiblioteka.Ksiazka KsiazkaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceBiblioteka.Autor Autor
        {
            get
            {
                return this.AutorField;
            }
            set
            {
                this.AutorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdAutora
        {
            get
            {
                return this.IdAutoraField;
            }
            set
            {
                this.IdAutoraField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdKsiazki
        {
            get
            {
                return this.IdKsiazkiField;
            }
            set
            {
                this.IdKsiazkiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsActive
        {
            get
            {
                return this.IsActiveField;
            }
            set
            {
                this.IsActiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceBiblioteka.Ksiazka Ksiazka
        {
            get
            {
                return this.KsiazkaField;
            }
            set
            {
                this.KsiazkaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ksiazka", Namespace="http://schemas.datacontract.org/2004/07/WcfProjektFirmy.Model.Entieties")]
    public partial class Ksiazka : object
    {
        
        private System.Collections.Generic.List<ServiceReferenceBiblioteka.Egzemplarz> EgzemplarzField;
        
        private ServiceReferenceBiblioteka.Gatunek GatunekField;
        
        private int IdGatunkuField;
        
        private int IdKsiazkiField;
        
        private System.Nullable<bool> IsActiveField;
        
        private System.Collections.Generic.List<ServiceReferenceBiblioteka.Ksiazka_Autor> Ksiazka_AutorField;
        
        private System.Nullable<int> LiczbaEgzDostepnychField;
        
        private string TytulField;
        
        private System.Collections.Generic.List<ServiceReferenceBiblioteka.Zamowienia> ZamowieniaField;
        
        private System.Collections.Generic.List<ServiceReferenceBiblioteka.Zamowienia> Zamowienia1Field;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceReferenceBiblioteka.Egzemplarz> Egzemplarz
        {
            get
            {
                return this.EgzemplarzField;
            }
            set
            {
                this.EgzemplarzField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceBiblioteka.Gatunek Gatunek
        {
            get
            {
                return this.GatunekField;
            }
            set
            {
                this.GatunekField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdGatunku
        {
            get
            {
                return this.IdGatunkuField;
            }
            set
            {
                this.IdGatunkuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdKsiazki
        {
            get
            {
                return this.IdKsiazkiField;
            }
            set
            {
                this.IdKsiazkiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsActive
        {
            get
            {
                return this.IsActiveField;
            }
            set
            {
                this.IsActiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceReferenceBiblioteka.Ksiazka_Autor> Ksiazka_Autor
        {
            get
            {
                return this.Ksiazka_AutorField;
            }
            set
            {
                this.Ksiazka_AutorField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> LiczbaEgzDostepnych
        {
            get
            {
                return this.LiczbaEgzDostepnychField;
            }
            set
            {
                this.LiczbaEgzDostepnychField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Tytul
        {
            get
            {
                return this.TytulField;
            }
            set
            {
                this.TytulField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceReferenceBiblioteka.Zamowienia> Zamowienia
        {
            get
            {
                return this.ZamowieniaField;
            }
            set
            {
                this.ZamowieniaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceReferenceBiblioteka.Zamowienia> Zamowienia1
        {
            get
            {
                return this.Zamowienia1Field;
            }
            set
            {
                this.Zamowienia1Field = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Gatunek", Namespace="http://schemas.datacontract.org/2004/07/WcfProjektFirmy.Model.Entieties")]
    public partial class Gatunek : object
    {
        
        private int IdGatunkuField;
        
        private System.Nullable<bool> IsActiveField;
        
        private System.Collections.Generic.List<ServiceReferenceBiblioteka.Ksiazka> KsiazkaField;
        
        private string NazwaGatunkuField;
        
        private string OpisField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdGatunku
        {
            get
            {
                return this.IdGatunkuField;
            }
            set
            {
                this.IdGatunkuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsActive
        {
            get
            {
                return this.IsActiveField;
            }
            set
            {
                this.IsActiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceReferenceBiblioteka.Ksiazka> Ksiazka
        {
            get
            {
                return this.KsiazkaField;
            }
            set
            {
                this.KsiazkaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NazwaGatunku
        {
            get
            {
                return this.NazwaGatunkuField;
            }
            set
            {
                this.NazwaGatunkuField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Opis
        {
            get
            {
                return this.OpisField;
            }
            set
            {
                this.OpisField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Egzemplarz", Namespace="http://schemas.datacontract.org/2004/07/WcfProjektFirmy.Model.Entieties")]
    public partial class Egzemplarz : object
    {
        
        private ServiceReferenceBiblioteka.Czytelnik CzytelnikField;
        
        private System.Nullable<System.DateTime> DataOddaniaField;
        
        private System.Nullable<System.DateTime> DataWypozyczeniaField;
        
        private System.Nullable<int> IdCzytelnikaField;
        
        private int IdEgzemplarzaField;
        
        private int IdKsiazkiField;
        
        private System.Nullable<int> IdPracownikaField;
        
        private System.Nullable<bool> IsActiveField;
        
        private ServiceReferenceBiblioteka.Ksiazka KsiazkaField;
        
        private ServiceReferenceBiblioteka.Pracownicy PracownicyField;
        
        private int RokWydaniaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceBiblioteka.Czytelnik Czytelnik
        {
            get
            {
                return this.CzytelnikField;
            }
            set
            {
                this.CzytelnikField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataOddania
        {
            get
            {
                return this.DataOddaniaField;
            }
            set
            {
                this.DataOddaniaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DataWypozyczenia
        {
            get
            {
                return this.DataWypozyczeniaField;
            }
            set
            {
                this.DataWypozyczeniaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdCzytelnika
        {
            get
            {
                return this.IdCzytelnikaField;
            }
            set
            {
                this.IdCzytelnikaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdEgzemplarza
        {
            get
            {
                return this.IdEgzemplarzaField;
            }
            set
            {
                this.IdEgzemplarzaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdKsiazki
        {
            get
            {
                return this.IdKsiazkiField;
            }
            set
            {
                this.IdKsiazkiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdPracownika
        {
            get
            {
                return this.IdPracownikaField;
            }
            set
            {
                this.IdPracownikaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsActive
        {
            get
            {
                return this.IsActiveField;
            }
            set
            {
                this.IsActiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceBiblioteka.Ksiazka Ksiazka
        {
            get
            {
                return this.KsiazkaField;
            }
            set
            {
                this.KsiazkaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceBiblioteka.Pracownicy Pracownicy
        {
            get
            {
                return this.PracownicyField;
            }
            set
            {
                this.PracownicyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RokWydania
        {
            get
            {
                return this.RokWydaniaField;
            }
            set
            {
                this.RokWydaniaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Zamowienia", Namespace="http://schemas.datacontract.org/2004/07/WcfProjektFirmy.Model.Entieties")]
    public partial class Zamowienia : object
    {
        
        private System.Nullable<int> IdKsiazkiField;
        
        private System.Nullable<int> IdKsiegarniField;
        
        private System.Nullable<int> IdPracownikaField;
        
        private int IdZamowieniaField;
        
        private System.Nullable<bool> IsActiveField;
        
        private ServiceReferenceBiblioteka.Ksiazka KsiazkaField;
        
        private ServiceReferenceBiblioteka.Ksiazka Ksiazka1Field;
        
        private ServiceReferenceBiblioteka.Ksiegarnia KsiegarniaField;
        
        private ServiceReferenceBiblioteka.Pracownicy PracownicyField;
        
        private System.Nullable<int> RokWydaniaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdKsiazki
        {
            get
            {
                return this.IdKsiazkiField;
            }
            set
            {
                this.IdKsiazkiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdKsiegarni
        {
            get
            {
                return this.IdKsiegarniField;
            }
            set
            {
                this.IdKsiegarniField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdPracownika
        {
            get
            {
                return this.IdPracownikaField;
            }
            set
            {
                this.IdPracownikaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdZamowienia
        {
            get
            {
                return this.IdZamowieniaField;
            }
            set
            {
                this.IdZamowieniaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsActive
        {
            get
            {
                return this.IsActiveField;
            }
            set
            {
                this.IsActiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceBiblioteka.Ksiazka Ksiazka
        {
            get
            {
                return this.KsiazkaField;
            }
            set
            {
                this.KsiazkaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceBiblioteka.Ksiazka Ksiazka1
        {
            get
            {
                return this.Ksiazka1Field;
            }
            set
            {
                this.Ksiazka1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceBiblioteka.Ksiegarnia Ksiegarnia
        {
            get
            {
                return this.KsiegarniaField;
            }
            set
            {
                this.KsiegarniaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceBiblioteka.Pracownicy Pracownicy
        {
            get
            {
                return this.PracownicyField;
            }
            set
            {
                this.PracownicyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> RokWydania
        {
            get
            {
                return this.RokWydaniaField;
            }
            set
            {
                this.RokWydaniaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Czytelnik", Namespace="http://schemas.datacontract.org/2004/07/WcfProjektFirmy.Model.Entieties")]
    public partial class Czytelnik : object
    {
        
        private string AdresField;
        
        private System.Collections.Generic.List<ServiceReferenceBiblioteka.Egzemplarz> EgzemplarzField;
        
        private int IdCzytelnikaField;
        
        private string ImieField;
        
        private System.Nullable<bool> IsActiveField;
        
        private string NazwiskoField;
        
        private long PeselField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adres
        {
            get
            {
                return this.AdresField;
            }
            set
            {
                this.AdresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceReferenceBiblioteka.Egzemplarz> Egzemplarz
        {
            get
            {
                return this.EgzemplarzField;
            }
            set
            {
                this.EgzemplarzField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdCzytelnika
        {
            get
            {
                return this.IdCzytelnikaField;
            }
            set
            {
                this.IdCzytelnikaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Imie
        {
            get
            {
                return this.ImieField;
            }
            set
            {
                this.ImieField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsActive
        {
            get
            {
                return this.IsActiveField;
            }
            set
            {
                this.IsActiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nazwisko
        {
            get
            {
                return this.NazwiskoField;
            }
            set
            {
                this.NazwiskoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Pesel
        {
            get
            {
                return this.PeselField;
            }
            set
            {
                this.PeselField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Pracownicy", Namespace="http://schemas.datacontract.org/2004/07/WcfProjektFirmy.Model.Entieties")]
    public partial class Pracownicy : object
    {
        
        private System.Collections.Generic.List<ServiceReferenceBiblioteka.Egzemplarz> EgzemplarzField;
        
        private ServiceReferenceBiblioteka.FilieBiblioteki FilieBibliotekiField;
        
        private System.Nullable<int> IdFiliiField;
        
        private int IdPracownikaField;
        
        private string ImieField;
        
        private System.Nullable<bool> IsActiveField;
        
        private string NazwiskoField;
        
        private string PeselField;
        
        private System.Collections.Generic.List<ServiceReferenceBiblioteka.Zamowienia> ZamowieniaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceReferenceBiblioteka.Egzemplarz> Egzemplarz
        {
            get
            {
                return this.EgzemplarzField;
            }
            set
            {
                this.EgzemplarzField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ServiceReferenceBiblioteka.FilieBiblioteki FilieBiblioteki
        {
            get
            {
                return this.FilieBibliotekiField;
            }
            set
            {
                this.FilieBibliotekiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> IdFilii
        {
            get
            {
                return this.IdFiliiField;
            }
            set
            {
                this.IdFiliiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdPracownika
        {
            get
            {
                return this.IdPracownikaField;
            }
            set
            {
                this.IdPracownikaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Imie
        {
            get
            {
                return this.ImieField;
            }
            set
            {
                this.ImieField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsActive
        {
            get
            {
                return this.IsActiveField;
            }
            set
            {
                this.IsActiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nazwisko
        {
            get
            {
                return this.NazwiskoField;
            }
            set
            {
                this.NazwiskoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pesel
        {
            get
            {
                return this.PeselField;
            }
            set
            {
                this.PeselField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceReferenceBiblioteka.Zamowienia> Zamowienia
        {
            get
            {
                return this.ZamowieniaField;
            }
            set
            {
                this.ZamowieniaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FilieBiblioteki", Namespace="http://schemas.datacontract.org/2004/07/WcfProjektFirmy.Model.Entieties")]
    public partial class FilieBiblioteki : object
    {
        
        private string AdresField;
        
        private int IdFiliField;
        
        private System.Nullable<bool> IsActiveField;
        
        private string NazwaField;
        
        private System.Collections.Generic.List<ServiceReferenceBiblioteka.Pracownicy> PracownicyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adres
        {
            get
            {
                return this.AdresField;
            }
            set
            {
                this.AdresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdFili
        {
            get
            {
                return this.IdFiliField;
            }
            set
            {
                this.IdFiliField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsActive
        {
            get
            {
                return this.IsActiveField;
            }
            set
            {
                this.IsActiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nazwa
        {
            get
            {
                return this.NazwaField;
            }
            set
            {
                this.NazwaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceReferenceBiblioteka.Pracownicy> Pracownicy
        {
            get
            {
                return this.PracownicyField;
            }
            set
            {
                this.PracownicyField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Ksiegarnia", Namespace="http://schemas.datacontract.org/2004/07/WcfProjektFirmy.Model.Entieties")]
    public partial class Ksiegarnia : object
    {
        
        private string AdresField;
        
        private int IdKsiegarniField;
        
        private System.Nullable<bool> IsActiveField;
        
        private string NazwaField;
        
        private System.Collections.Generic.List<ServiceReferenceBiblioteka.Zamowienia> ZamowieniaField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Adres
        {
            get
            {
                return this.AdresField;
            }
            set
            {
                this.AdresField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int IdKsiegarni
        {
            get
            {
                return this.IdKsiegarniField;
            }
            set
            {
                this.IdKsiegarniField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> IsActive
        {
            get
            {
                return this.IsActiveField;
            }
            set
            {
                this.IsActiveField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nazwa
        {
            get
            {
                return this.NazwaField;
            }
            set
            {
                this.NazwaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<ServiceReferenceBiblioteka.Zamowienia> Zamowienia
        {
            get
            {
                return this.ZamowieniaField;
            }
            set
            {
                this.ZamowieniaField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReferenceBiblioteka.IServiceBiblioteka")]
    public interface IServiceBiblioteka
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBiblioteka/GetData", ReplyAction="http://tempuri.org/IServiceBiblioteka/GetDataResponse")]
        ServiceReferenceBiblioteka.GetDataResponse GetData(ServiceReferenceBiblioteka.GetDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBiblioteka/GetData", ReplyAction="http://tempuri.org/IServiceBiblioteka/GetDataResponse")]
        System.Threading.Tasks.Task<ServiceReferenceBiblioteka.GetDataResponse> GetDataAsync(ServiceReferenceBiblioteka.GetDataRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBiblioteka/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IServiceBiblioteka/GetDataUsingDataContractResponse")]
        ServiceReferenceBiblioteka.GetDataUsingDataContractResponse GetDataUsingDataContract(ServiceReferenceBiblioteka.GetDataUsingDataContractRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBiblioteka/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IServiceBiblioteka/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<ServiceReferenceBiblioteka.GetDataUsingDataContractResponse> GetDataUsingDataContractAsync(ServiceReferenceBiblioteka.GetDataUsingDataContractRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBiblioteka/GetAutor", ReplyAction="http://tempuri.org/IServiceBiblioteka/GetAutorResponse")]
        ServiceReferenceBiblioteka.GetAutorResponse GetAutor(ServiceReferenceBiblioteka.GetAutorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBiblioteka/GetAutor", ReplyAction="http://tempuri.org/IServiceBiblioteka/GetAutorResponse")]
        System.Threading.Tasks.Task<ServiceReferenceBiblioteka.GetAutorResponse> GetAutorAsync(ServiceReferenceBiblioteka.GetAutorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBiblioteka/GetCzytelnik", ReplyAction="http://tempuri.org/IServiceBiblioteka/GetCzytelnikResponse")]
        ServiceReferenceBiblioteka.GetCzytelnikResponse GetCzytelnik(ServiceReferenceBiblioteka.GetCzytelnikRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBiblioteka/GetCzytelnik", ReplyAction="http://tempuri.org/IServiceBiblioteka/GetCzytelnikResponse")]
        System.Threading.Tasks.Task<ServiceReferenceBiblioteka.GetCzytelnikResponse> GetCzytelnikAsync(ServiceReferenceBiblioteka.GetCzytelnikRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBiblioteka/GetEgzemplarz", ReplyAction="http://tempuri.org/IServiceBiblioteka/GetEgzemplarzResponse")]
        ServiceReferenceBiblioteka.GetEgzemplarzResponse GetEgzemplarz(ServiceReferenceBiblioteka.GetEgzemplarzRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBiblioteka/GetEgzemplarz", ReplyAction="http://tempuri.org/IServiceBiblioteka/GetEgzemplarzResponse")]
        System.Threading.Tasks.Task<ServiceReferenceBiblioteka.GetEgzemplarzResponse> GetEgzemplarzAsync(ServiceReferenceBiblioteka.GetEgzemplarzRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBiblioteka/GetFilie", ReplyAction="http://tempuri.org/IServiceBiblioteka/GetFilieResponse")]
        ServiceReferenceBiblioteka.GetFilieResponse GetFilie(ServiceReferenceBiblioteka.GetFilieRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBiblioteka/GetFilie", ReplyAction="http://tempuri.org/IServiceBiblioteka/GetFilieResponse")]
        System.Threading.Tasks.Task<ServiceReferenceBiblioteka.GetFilieResponse> GetFilieAsync(ServiceReferenceBiblioteka.GetFilieRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBiblioteka/GetGatunek", ReplyAction="http://tempuri.org/IServiceBiblioteka/GetGatunekResponse")]
        ServiceReferenceBiblioteka.GetGatunekResponse GetGatunek(ServiceReferenceBiblioteka.GetGatunekRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBiblioteka/GetGatunek", ReplyAction="http://tempuri.org/IServiceBiblioteka/GetGatunekResponse")]
        System.Threading.Tasks.Task<ServiceReferenceBiblioteka.GetGatunekResponse> GetGatunekAsync(ServiceReferenceBiblioteka.GetGatunekRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBiblioteka/GetKsiazka", ReplyAction="http://tempuri.org/IServiceBiblioteka/GetKsiazkaResponse")]
        ServiceReferenceBiblioteka.GetKsiazkaResponse GetKsiazka(ServiceReferenceBiblioteka.GetKsiazkaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBiblioteka/GetKsiazka", ReplyAction="http://tempuri.org/IServiceBiblioteka/GetKsiazkaResponse")]
        System.Threading.Tasks.Task<ServiceReferenceBiblioteka.GetKsiazkaResponse> GetKsiazkaAsync(ServiceReferenceBiblioteka.GetKsiazkaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBiblioteka/GetKsiegarnia", ReplyAction="http://tempuri.org/IServiceBiblioteka/GetKsiegarniaResponse")]
        ServiceReferenceBiblioteka.GetKsiegarniaResponse GetKsiegarnia(ServiceReferenceBiblioteka.GetKsiegarniaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBiblioteka/GetKsiegarnia", ReplyAction="http://tempuri.org/IServiceBiblioteka/GetKsiegarniaResponse")]
        System.Threading.Tasks.Task<ServiceReferenceBiblioteka.GetKsiegarniaResponse> GetKsiegarniaAsync(ServiceReferenceBiblioteka.GetKsiegarniaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBiblioteka/GetPracownicy", ReplyAction="http://tempuri.org/IServiceBiblioteka/GetPracownicyResponse")]
        ServiceReferenceBiblioteka.GetPracownicyResponse GetPracownicy(ServiceReferenceBiblioteka.GetPracownicyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBiblioteka/GetPracownicy", ReplyAction="http://tempuri.org/IServiceBiblioteka/GetPracownicyResponse")]
        System.Threading.Tasks.Task<ServiceReferenceBiblioteka.GetPracownicyResponse> GetPracownicyAsync(ServiceReferenceBiblioteka.GetPracownicyRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBiblioteka/GetZamowienia", ReplyAction="http://tempuri.org/IServiceBiblioteka/GetZamowieniaResponse")]
        ServiceReferenceBiblioteka.GetZamowieniaResponse GetZamowienia(ServiceReferenceBiblioteka.GetZamowieniaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBiblioteka/GetZamowienia", ReplyAction="http://tempuri.org/IServiceBiblioteka/GetZamowieniaResponse")]
        System.Threading.Tasks.Task<ServiceReferenceBiblioteka.GetZamowieniaResponse> GetZamowieniaAsync(ServiceReferenceBiblioteka.GetZamowieniaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBiblioteka/AddAutor", ReplyAction="http://tempuri.org/IServiceBiblioteka/AddAutorResponse")]
        ServiceReferenceBiblioteka.AddAutorResponse AddAutor(ServiceReferenceBiblioteka.AddAutorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceBiblioteka/AddAutor", ReplyAction="http://tempuri.org/IServiceBiblioteka/AddAutorResponse")]
        System.Threading.Tasks.Task<ServiceReferenceBiblioteka.AddAutorResponse> AddAutorAsync(ServiceReferenceBiblioteka.AddAutorRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetData", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public int value;
        
        public GetDataRequest()
        {
        }
        
        public GetDataRequest(int value)
        {
            this.value = value;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public string GetDataResult;
        
        public GetDataResponse()
        {
        }
        
        public GetDataResponse(string GetDataResult)
        {
            this.GetDataResult = GetDataResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataUsingDataContract", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataUsingDataContractRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReferenceBiblioteka.CompositeType composite;
        
        public GetDataUsingDataContractRequest()
        {
        }
        
        public GetDataUsingDataContractRequest(ServiceReferenceBiblioteka.CompositeType composite)
        {
            this.composite = composite;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetDataUsingDataContractResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetDataUsingDataContractResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReferenceBiblioteka.CompositeType GetDataUsingDataContractResult;
        
        public GetDataUsingDataContractResponse()
        {
        }
        
        public GetDataUsingDataContractResponse(ServiceReferenceBiblioteka.CompositeType GetDataUsingDataContractResult)
        {
            this.GetDataUsingDataContractResult = GetDataUsingDataContractResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAutor", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAutorRequest
    {
        
        public GetAutorRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetAutorResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetAutorResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<ServiceReferenceBiblioteka.AutorForView> GetAutorResult;
        
        public GetAutorResponse()
        {
        }
        
        public GetAutorResponse(System.Collections.Generic.List<ServiceReferenceBiblioteka.AutorForView> GetAutorResult)
        {
            this.GetAutorResult = GetAutorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCzytelnik", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCzytelnikRequest
    {
        
        public GetCzytelnikRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCzytelnikResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetCzytelnikResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<ServiceReferenceBiblioteka.CzytelnikForView> GetCzytelnikResult;
        
        public GetCzytelnikResponse()
        {
        }
        
        public GetCzytelnikResponse(System.Collections.Generic.List<ServiceReferenceBiblioteka.CzytelnikForView> GetCzytelnikResult)
        {
            this.GetCzytelnikResult = GetCzytelnikResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEgzemplarz", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetEgzemplarzRequest
    {
        
        public GetEgzemplarzRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetEgzemplarzResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetEgzemplarzResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<ServiceReferenceBiblioteka.EgzemplarzForView> GetEgzemplarzResult;
        
        public GetEgzemplarzResponse()
        {
        }
        
        public GetEgzemplarzResponse(System.Collections.Generic.List<ServiceReferenceBiblioteka.EgzemplarzForView> GetEgzemplarzResult)
        {
            this.GetEgzemplarzResult = GetEgzemplarzResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFilie", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetFilieRequest
    {
        
        public GetFilieRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetFilieResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetFilieResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<ServiceReferenceBiblioteka.FilieForView> GetFilieResult;
        
        public GetFilieResponse()
        {
        }
        
        public GetFilieResponse(System.Collections.Generic.List<ServiceReferenceBiblioteka.FilieForView> GetFilieResult)
        {
            this.GetFilieResult = GetFilieResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetGatunek", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetGatunekRequest
    {
        
        public GetGatunekRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetGatunekResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetGatunekResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<ServiceReferenceBiblioteka.GatunekForView> GetGatunekResult;
        
        public GetGatunekResponse()
        {
        }
        
        public GetGatunekResponse(System.Collections.Generic.List<ServiceReferenceBiblioteka.GatunekForView> GetGatunekResult)
        {
            this.GetGatunekResult = GetGatunekResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetKsiazka", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetKsiazkaRequest
    {
        
        public GetKsiazkaRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetKsiazkaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetKsiazkaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<ServiceReferenceBiblioteka.KsiazkaForView> GetKsiazkaResult;
        
        public GetKsiazkaResponse()
        {
        }
        
        public GetKsiazkaResponse(System.Collections.Generic.List<ServiceReferenceBiblioteka.KsiazkaForView> GetKsiazkaResult)
        {
            this.GetKsiazkaResult = GetKsiazkaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetKsiegarnia", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetKsiegarniaRequest
    {
        
        public GetKsiegarniaRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetKsiegarniaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetKsiegarniaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<ServiceReferenceBiblioteka.KsiegarniaForView> GetKsiegarniaResult;
        
        public GetKsiegarniaResponse()
        {
        }
        
        public GetKsiegarniaResponse(System.Collections.Generic.List<ServiceReferenceBiblioteka.KsiegarniaForView> GetKsiegarniaResult)
        {
            this.GetKsiegarniaResult = GetKsiegarniaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPracownicy", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPracownicyRequest
    {
        
        public GetPracownicyRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetPracownicyResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetPracownicyResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<ServiceReferenceBiblioteka.PracownicyForView> GetPracownicyResult;
        
        public GetPracownicyResponse()
        {
        }
        
        public GetPracownicyResponse(System.Collections.Generic.List<ServiceReferenceBiblioteka.PracownicyForView> GetPracownicyResult)
        {
            this.GetPracownicyResult = GetPracownicyResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetZamowienia", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetZamowieniaRequest
    {
        
        public GetZamowieniaRequest()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetZamowieniaResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class GetZamowieniaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.Collections.Generic.List<ServiceReferenceBiblioteka.ZamowieniaForView> GetZamowieniaResult;
        
        public GetZamowieniaResponse()
        {
        }
        
        public GetZamowieniaResponse(System.Collections.Generic.List<ServiceReferenceBiblioteka.ZamowieniaForView> GetZamowieniaResult)
        {
            this.GetZamowieniaResult = GetZamowieniaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddAutor", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddAutorRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public ServiceReferenceBiblioteka.Autor autor;
        
        public AddAutorRequest()
        {
        }
        
        public AddAutorRequest(ServiceReferenceBiblioteka.Autor autor)
        {
            this.autor = autor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddAutorResponse", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class AddAutorResponse
    {
        
        public AddAutorResponse()
        {
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface IServiceBibliotekaChannel : ServiceReferenceBiblioteka.IServiceBiblioteka, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class ServiceBibliotekaClient : System.ServiceModel.ClientBase<ServiceReferenceBiblioteka.IServiceBiblioteka>, ServiceReferenceBiblioteka.IServiceBiblioteka
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ServiceBibliotekaClient() : 
                base(ServiceBibliotekaClient.GetDefaultBinding(), ServiceBibliotekaClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IServiceBiblioteka.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceBibliotekaClient(EndpointConfiguration endpointConfiguration) : 
                base(ServiceBibliotekaClient.GetBindingForEndpoint(endpointConfiguration), ServiceBibliotekaClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceBibliotekaClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ServiceBibliotekaClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceBibliotekaClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ServiceBibliotekaClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ServiceBibliotekaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public ServiceReferenceBiblioteka.GetDataResponse GetData(ServiceReferenceBiblioteka.GetDataRequest request)
        {
            return base.Channel.GetData(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceBiblioteka.GetDataResponse> GetDataAsync(ServiceReferenceBiblioteka.GetDataRequest request)
        {
            return base.Channel.GetDataAsync(request);
        }
        
        public ServiceReferenceBiblioteka.GetDataUsingDataContractResponse GetDataUsingDataContract(ServiceReferenceBiblioteka.GetDataUsingDataContractRequest request)
        {
            return base.Channel.GetDataUsingDataContract(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceBiblioteka.GetDataUsingDataContractResponse> GetDataUsingDataContractAsync(ServiceReferenceBiblioteka.GetDataUsingDataContractRequest request)
        {
            return base.Channel.GetDataUsingDataContractAsync(request);
        }
        
        public ServiceReferenceBiblioteka.GetAutorResponse GetAutor(ServiceReferenceBiblioteka.GetAutorRequest request)
        {
            return base.Channel.GetAutor(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceBiblioteka.GetAutorResponse> GetAutorAsync(ServiceReferenceBiblioteka.GetAutorRequest request)
        {
            return base.Channel.GetAutorAsync(request);
        }
        
        public ServiceReferenceBiblioteka.GetCzytelnikResponse GetCzytelnik(ServiceReferenceBiblioteka.GetCzytelnikRequest request)
        {
            return base.Channel.GetCzytelnik(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceBiblioteka.GetCzytelnikResponse> GetCzytelnikAsync(ServiceReferenceBiblioteka.GetCzytelnikRequest request)
        {
            return base.Channel.GetCzytelnikAsync(request);
        }
        
        public ServiceReferenceBiblioteka.GetEgzemplarzResponse GetEgzemplarz(ServiceReferenceBiblioteka.GetEgzemplarzRequest request)
        {
            return base.Channel.GetEgzemplarz(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceBiblioteka.GetEgzemplarzResponse> GetEgzemplarzAsync(ServiceReferenceBiblioteka.GetEgzemplarzRequest request)
        {
            return base.Channel.GetEgzemplarzAsync(request);
        }
        
        public ServiceReferenceBiblioteka.GetFilieResponse GetFilie(ServiceReferenceBiblioteka.GetFilieRequest request)
        {
            return base.Channel.GetFilie(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceBiblioteka.GetFilieResponse> GetFilieAsync(ServiceReferenceBiblioteka.GetFilieRequest request)
        {
            return base.Channel.GetFilieAsync(request);
        }
        
        public ServiceReferenceBiblioteka.GetGatunekResponse GetGatunek(ServiceReferenceBiblioteka.GetGatunekRequest request)
        {
            return base.Channel.GetGatunek(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceBiblioteka.GetGatunekResponse> GetGatunekAsync(ServiceReferenceBiblioteka.GetGatunekRequest request)
        {
            return base.Channel.GetGatunekAsync(request);
        }
        
        public ServiceReferenceBiblioteka.GetKsiazkaResponse GetKsiazka(ServiceReferenceBiblioteka.GetKsiazkaRequest request)
        {
            return base.Channel.GetKsiazka(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceBiblioteka.GetKsiazkaResponse> GetKsiazkaAsync(ServiceReferenceBiblioteka.GetKsiazkaRequest request)
        {
            return base.Channel.GetKsiazkaAsync(request);
        }
        
        public ServiceReferenceBiblioteka.GetKsiegarniaResponse GetKsiegarnia(ServiceReferenceBiblioteka.GetKsiegarniaRequest request)
        {
            return base.Channel.GetKsiegarnia(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceBiblioteka.GetKsiegarniaResponse> GetKsiegarniaAsync(ServiceReferenceBiblioteka.GetKsiegarniaRequest request)
        {
            return base.Channel.GetKsiegarniaAsync(request);
        }
        
        public ServiceReferenceBiblioteka.GetPracownicyResponse GetPracownicy(ServiceReferenceBiblioteka.GetPracownicyRequest request)
        {
            return base.Channel.GetPracownicy(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceBiblioteka.GetPracownicyResponse> GetPracownicyAsync(ServiceReferenceBiblioteka.GetPracownicyRequest request)
        {
            return base.Channel.GetPracownicyAsync(request);
        }
        
        public ServiceReferenceBiblioteka.GetZamowieniaResponse GetZamowienia(ServiceReferenceBiblioteka.GetZamowieniaRequest request)
        {
            return base.Channel.GetZamowienia(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceBiblioteka.GetZamowieniaResponse> GetZamowieniaAsync(ServiceReferenceBiblioteka.GetZamowieniaRequest request)
        {
            return base.Channel.GetZamowieniaAsync(request);
        }
        
        public ServiceReferenceBiblioteka.AddAutorResponse AddAutor(ServiceReferenceBiblioteka.AddAutorRequest request)
        {
            return base.Channel.AddAutor(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReferenceBiblioteka.AddAutorResponse> AddAutorAsync(ServiceReferenceBiblioteka.AddAutorRequest request)
        {
            return base.Channel.AddAutorAsync(request);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceBiblioteka))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IServiceBiblioteka))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.1.101:55555/ServiceBiblioteka.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ServiceBibliotekaClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IServiceBiblioteka);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ServiceBibliotekaClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IServiceBiblioteka);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IServiceBiblioteka,
        }
    }
}
